### PR TITLE
Fix admin

### PR DESCRIPTION
**Pull request by RomainLF**

### CODE REVIEW

**Review by FrancoisSalmon — DISMISSED** [review]
ok

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — CHANGES_REQUESTED** [review]

**Review by FrancoisSalmon — DISMISSED** [review]
ok

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by FrancoisSalmon — DISMISSED** [review]
ok for me

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Comment by LoicBrassart** [comment]
Conflicts

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by FrancoisSalmon — APPROVED** [review]
ok for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
