### PR TITLE
032 bdd modelisation

### PR DESCRIPTION
**Pull request by FrancoisSalmon**

### CODE REVIEW

**Review by RomainLF — DISMISSED** [review]

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Have you checked that all your paths are working? and the url's are better put in lower case

**Review by Gonaline — APPROVED** [review]
ok

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by LoicBrassart — DISMISSED** [review]
In a PR named "bdd modelisation" (SideNote: "DB modelization" would have been better :p), it's not normal to change App.jsx and to rename pictures.
Other than that, SnE!

**Review by RomainLF — DISMISSED** [review]

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Comment by FrancoisSalmon** [comment]
error in files suppress this one and creating another one called 032-bdd-modelisation-bis

**Pull request closed without merging**
