### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by NtGZeko**

### CODE REVIEW

**Review by FrancoisSalmon — APPROVED** [review]
ok

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Don't put me on reviewers until the DM has validated the pr.

**Review by FrancoisSalmon — APPROVED** [review]
ok for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
