### PR TITLE
proptypes, key prop and other console error corrections

### PR DESCRIPTION
**Pull request by FrancoisSalmon**

### CODE REVIEW

**Review by NtGZeko — DISMISSED** [review]
Good for me

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Review by NtGZeko — APPROVED** [review]
fix conflit

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LuigiMenez — CHANGES_REQUESTED** [review]
Fix conflict

**Review by NtGZeko — APPROVED** [review]

**Comment by NtGZeko** [comment]
good for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
