### PR TITLE
create pages nonProfessional & detail

### PR DESCRIPTION
**Pull request by Gonaline**

### CODE REVIEW

**Review by FrancoisSalmon — DISMISSED** [review]
ok for me

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Comment by LoicBrassart** [comment]
Conflicts

**Review by FrancoisSalmon — APPROVED** [review]
conflict resolved

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by FrancoisSalmon — APPROVED** [review]
ok

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Review by FrancoisSalmon — APPROVED** [review]
conflict fixed

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
